// 86 ancient Greek writers — name, fields, era (approx. floruit/lifespan), representative work.
// Dates are approximate and follow standard classical scholarship. BC unless noted.
window.AUTHORS = [
  {name:"Aeschines",fields:["Rhetorics"],era:"c. 389–314 BC",work:"Against Ctesiphon"},
  {name:"Aeschylus",fields:["Tragedy"],era:"c. 525–456 BC",work:"The Oresteia"},
  {name:"Aesop",fields:["Fables"],era:"c. 620–564 BC",work:"Aesop's Fables"},
  {name:"Alcaeus of Mytilene",fields:["Lyric Poetry"],era:"c. 625–580 BC",work:"lyric fragments"},
  {name:"Alcman",fields:["Lyric Poetry"],era:"7th century BC",work:"Partheneion (Maiden Songs)"},
  {name:"Anacreon",fields:["Lyric Poetry"],era:"c. 582–485 BC",work:"drinking and love songs"},
  {name:"Anaxagoras",fields:["Philosophy"],era:"c. 500–428 BC",work:"On Nature"},
  {name:"Anaximander",fields:["Philosophy","Mathematics"],era:"c. 610–546 BC",work:"On Nature"},
  {name:"Anaximenes",fields:["Philosophy","Mathematics"],era:"c. 586–526 BC",work:"On Nature"},
  {name:"Andocides",fields:["Rhetorics"],era:"c. 440–390 BC",work:"On the Mysteries"},
  {name:"Antiphon",fields:["Rhetorics"],era:"c. 480–411 BC",work:"Tetralogies"},
  {name:"Apollodorus of Carystus",fields:["Comedy"],era:"3rd century BC",work:"New Comedy plays"},
  {name:"Aristophanes",fields:["Comedy"],era:"c. 446–386 BC",work:"The Frogs"},
  {name:"Archimedes",fields:["Mathematics","Geometry"],era:"c. 287–212 BC",work:"On the Sphere and Cylinder"},
  {name:"Aristotle",fields:["Philosophy","Physics","Biology"],era:"384–322 BC",work:"Nicomachean Ethics"},
  {name:"Aratus",fields:["Poetry","Astronomy"],era:"c. 315–240 BC",work:"Phaenomena"},
  {name:"Arrian",fields:["History"],era:"c. 86–160 AD",work:"Anabasis of Alexander"},
  {name:"Athanasius of Alexandria",fields:["Theology"],era:"c. 296–373 AD",work:"On the Incarnation"},
  {name:"Bacchylides",fields:["Lyric Poetry"],era:"c. 518–451 BC",work:"Victory Odes"},
  {name:"Callimachus",fields:["Poetry"],era:"c. 310–240 BC",work:"Aetia"},
  {name:"Chionides",fields:["Comedy"],era:"5th century BC",work:"early Old Comedy"},
  {name:"Chrysippus",fields:["Philosophy"],era:"c. 279–206 BC",work:"logical writings (Stoicism)"},
  {name:"Claudius Ptolemy",fields:["Geography","Astronomy"],era:"c. 100–170 AD",work:"Almagest"},
  {name:"Clement of Alexandria",fields:["Theology","Philosophy"],era:"c. 150–215 AD",work:"Stromata"},
  {name:"Democritus",fields:["Philosophy","Chemistry"],era:"c. 460–370 BC",work:"atomic theory writings"},
  {name:"Demosthenes",fields:["Rhetorics","Politics"],era:"384–322 BC",work:"Philippics"},
  {name:"Dinarchus",fields:["Rhetorics"],era:"c. 361–291 BC",work:"Against Demosthenes"},
  {name:"Dinon",fields:["History"],era:"4th century BC",work:"Persica"},
  {name:"Diodorus",fields:["History"],era:"1st century BC",work:"Bibliotheca historica"},
  {name:"Diogenes Laërtius",fields:["History of Philosophy"],era:"3rd century AD",work:"Lives of Eminent Philosophers"},
  {name:"Duris of Samos",fields:["History"],era:"c. 350–281 BC",work:"Histories"},
  {name:"Epicurus",fields:["Philosophy"],era:"341–270 BC",work:"Letter to Menoeceus"},
  {name:"Epimenides of Knossos",fields:["Philosophy","Poetry"],era:"7th–6th century BC",work:"Cretica"},
  {name:"Eubulus",fields:["Comedy"],era:"4th century BC",work:"Middle Comedy plays"},
  {name:"Euclid of Megara",fields:["Mathematics","Geometry"],era:"c. 435–365 BC",work:"Megarian philosophy"},
  {name:"Euripides",fields:["Tragedy"],era:"c. 480–406 BC",work:"Medea"},
  {name:"Evagrius Ponticus",fields:["Theology"],era:"345–399 AD",work:"Praktikos"},
  {name:"Gorgias",fields:["Philosophy"],era:"c. 483–375 BC",work:"Encomium of Helen"},
  {name:"Hegemon of Thasos",fields:["Comedy"],era:"5th century BC",work:"parody verse"},
  {name:"Heraclitus",fields:["Philosophy"],era:"c. 535–475 BC",work:"On Nature"},
  {name:"Herodotus of Halicarnassus",fields:["History"],era:"c. 484–425 BC",work:"The Histories"},
  {name:"Hesiod",fields:["Epic Poetry"],era:"c. 750–650 BC",work:"Theogony"},
  {name:"Hippocrates of Cos",fields:["Medicine"],era:"c. 460–370 BC",work:"Hippocratic Corpus"},
  {name:"Homer",fields:["Epic Poetry"],era:"c. 8th century BC",work:"The Iliad & The Odyssey"},
  {name:"Hypereides",fields:["Rhetorics"],era:"390–322 BC",work:"Funeral Oration"},
  {name:"Iamblichus",fields:["Philosophy"],era:"c. 245–325 AD",work:"On the Mysteries"},
  {name:"Ibycus of Rhegium",fields:["Lyric Poetry"],era:"6th century BC",work:"erotic lyric fragments"},
  {name:"Irenaeus",fields:["Theology","Philosophy"],era:"c. 130–202 AD",work:"Against Heresies"},
  {name:"Isaeus",fields:["Rhetorics","Logography"],era:"c. 420–340 BC",work:"On the Estate speeches"},
  {name:"Isocrates",fields:["Rhetorics"],era:"436–338 BC",work:"Panegyricus"},
  {name:"Justin the Martyr",fields:["Theology","Philosophy"],era:"c. 100–165 AD",work:"First Apology"},
  {name:"Leucippus",fields:["Philosophy","Atomism"],era:"5th century BC",work:"The Great World-System"},
  {name:"Lucian",fields:["Satire","Rhetoric"],era:"c. 125–180 AD",work:"A True Story"},
  {name:"Luke the Evangelist",fields:["Theology","Medicine","History"],era:"1st century AD",work:"Gospel of Luke & Acts"},
  {name:"Lycurgus of Athens",fields:["Rhetorics"],era:"c. 390–324 BC",work:"Against Leocrates"},
  {name:"Lysias",fields:["Logography","Rhetorics"],era:"c. 445–380 BC",work:"Against Eratosthenes"},
  {name:"Maximus the Confessor",fields:["Theology","Philosophy"],era:"c. 580–662 AD",work:"Ambigua"},
  {name:"Menander",fields:["Comedy"],era:"c. 342–290 BC",work:"Dyskolos"},
  {name:"Melissus of Samos",fields:["Philosophy"],era:"5th century BC",work:"On Nature"},
  {name:"Nicomachus of Gerasa",fields:["Mathematics"],era:"c. 60–120 AD",work:"Introduction to Arithmetic"},
  {name:"Origen",fields:["Theology","Philosophy"],era:"c. 184–253 AD",work:"On First Principles"},
  {name:"Papias of Hierapolis",fields:["Theology"],era:"c. 60–130 AD",work:"Exposition of the Sayings of the Lord"},
  {name:"Parmenides",fields:["Philosophy"],era:"c. 515–450 BC",work:"On Nature"},
  {name:"Pherecydes of Athens",fields:["Mythography","Logography"],era:"5th century BC",work:"Historiai"},
  {name:"Philo of Alexandria",fields:["Theology","Philosophy"],era:"c. 25 BC–50 AD",work:"On the Creation"},
  {name:"Pindar",fields:["Lyric Poetry"],era:"c. 518–438 BC",work:"Olympian Odes"},
  {name:"Plato",fields:["Philosophy"],era:"c. 428–348 BC",work:"The Republic"},
  {name:"Plutarch",fields:["History","Biography","Philosophy"],era:"c. 46–120 AD",work:"Parallel Lives"},
  {name:"Posidippus",fields:["Comedy"],era:"3rd century BC",work:"New Comedy plays"},
  {name:"Protagoras",fields:["Philosophy"],era:"c. 490–420 BC",work:"On Truth"},
  {name:"Sappho of Lesbos",fields:["Lyric Poetry"],era:"c. 630–570 BC",work:"Ode to Aphrodite"},
  {name:"Simonides",fields:["Lyric Poetry"],era:"c. 556–468 BC",work:"epigrams and odes"},
  {name:"Solon",fields:["Politics","Philosophy"],era:"c. 630–560 BC",work:"political elegies"},
  {name:"Sophocles",fields:["Tragedy"],era:"c. 497–406 BC",work:"Oedipus Rex"},
  {name:"Stesichorus",fields:["Lyric Poetry"],era:"c. 630–555 BC",work:"Palinode"},
  {name:"Strattis",fields:["Comedy"],era:"5th century BC",work:"Old Comedy plays"},
  {name:"Thales of Miletus",fields:["Philosophy","Mathematics","Astronomy","Physics"],era:"c. 626–548 BC",work:"founding Milesian thought"},
  {name:"Theocritus",fields:["Bucolic Poetry"],era:"c. 300–260 BC",work:"Idylls"},
  {name:"Theognis of Megara",fields:["Lyric Poetry"],era:"6th century BC",work:"Elegies"},
  {name:"Theopompus",fields:["History"],era:"c. 380–315 BC",work:"Philippica"},
  {name:"Thucydides",fields:["History"],era:"c. 460–400 BC",work:"History of the Peloponnesian War"},
  {name:"Xenarchus of Seleucia",fields:["Philosophy","Philology"],era:"1st century BC",work:"Against the Fifth Substance"},
  {name:"Xenophanes",fields:["Philosophy","Theology"],era:"c. 570–475 BC",work:"Silloi"},
  {name:"Xenophon",fields:["History"],era:"c. 430–354 BC",work:"Anabasis"},
  {name:"Zeno of Citium",fields:["Philosophy"],era:"c. 334–262 BC",work:"founder of Stoicism"},
  {name:"Zeno of Elea",fields:["Philosophy"],era:"c. 490–430 BC",work:"Paradoxes of Motion"}
];
